name: MixedAchievements
version: ${project.version}
main: ch.mixin.mixedAchievements.main.MixedAchievements
api-version: 1.16

commands:
  mx:
    description: The Root Command for MixedAchievments with Prefix mx.